"""Filesystem-backed views for platform journey evidence snapshots.

The store is intentionally read-only and non-destructive. It exposes the latest
and indexed platform journey evidence files generated by scripts/platform_journey.py
without introducing database dependencies or AI/vector runtime dependencies.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

DEFAULT_JOURNEY_EVIDENCE_DIR = Path("runtime") / "evidence" / "platform-journey"
JOURNEY_EVIDENCE_PREFIX = "journey_"
JOURNEY_EVIDENCE_SUFFIX = ".json"


def repo_root() -> Path:
    current = Path(__file__).resolve()
    for parent in current.parents:
        if (parent / "apps" / "api").exists() and (parent / "scripts").exists():
            return parent
    return current.parents[3]


def resolve_evidence_dir(evidence_dir: str | None = None) -> Path:
    if evidence_dir:
        path = Path(evidence_dir)
        return path if path.is_absolute() else repo_root() / path
    return repo_root() / DEFAULT_JOURNEY_EVIDENCE_DIR


def is_journey_evidence_file(path: Path) -> bool:
    return path.is_file() and path.name.startswith(JOURNEY_EVIDENCE_PREFIX) and path.suffix == JOURNEY_EVIDENCE_SUFFIX


def _safe_read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"journey_evidence_must_be_json_object:{path}")
    return payload


def _evidence_item(path: Path, include_payload: bool = False) -> dict[str, Any]:
    stat = path.stat()
    item: dict[str, Any] = {
        "file_name": path.name,
        "path": str(path),
        "size_bytes": stat.st_size,
        "modified_epoch_s": int(stat.st_mtime),
    }
    try:
        payload = _safe_read_json(path)
        item.update(
            {
                "valid_json": True,
                "plan": payload.get("plan"),
                "timestamp_utc": payload.get("timestamp_utc"),
                "journey_status": payload.get("journey_status"),
                "journey_complete": payload.get("journey_complete"),
                "safe_to_run_without_ai": payload.get("safe_to_run_without_ai"),
                "ai_services_blocking": payload.get("ai_services_blocking"),
                "blocking_issue_count": payload.get("blocking_issue_count"),
                "degraded_capabilities": list(payload.get("degraded_capabilities") or []),
            }
        )
        if include_payload:
            item["payload"] = payload
    except Exception as exc:
        item.update(
            {
                "valid_json": False,
                "error": "invalid_journey_evidence",
                "error_type": type(exc).__name__,
            }
        )
    return item


def list_platform_journey_evidence(
    *,
    evidence_dir: str | None = None,
    limit: int = 20,
) -> dict[str, Any]:
    directory = resolve_evidence_dir(evidence_dir)
    if not directory.exists():
        return {
            "plan": "platform_product_journey_evidence_index",
            "evidence_dir": str(directory),
            "exists": False,
            "snapshot_count": 0,
            "snapshots": [],
            "destructive_action_executed": False,
            "migration_executed": False,
            "downgrade_executed": False,
        }

    files = sorted(
        [path for path in directory.iterdir() if is_journey_evidence_file(path)],
        key=lambda path: (path.stat().st_mtime, path.name),
        reverse=True,
    )
    limited = files[: max(1, min(limit, 100))]
    snapshots = [_evidence_item(path, include_payload=False) for path in limited]
    return {
        "plan": "platform_product_journey_evidence_index",
        "evidence_dir": str(directory),
        "exists": True,
        "snapshot_count": len(files),
        "returned_count": len(snapshots),
        "snapshots": snapshots,
        "destructive_action_executed": False,
        "migration_executed": False,
        "downgrade_executed": False,
    }


def get_latest_platform_journey_evidence(
    *,
    evidence_dir: str | None = None,
) -> dict[str, Any]:
    index = list_platform_journey_evidence(evidence_dir=evidence_dir, limit=1)
    if not index["snapshots"]:
        return {
            "plan": "platform_product_journey_evidence_latest",
            "evidence_dir": index["evidence_dir"],
            "found": False,
            "snapshot": None,
            "destructive_action_executed": False,
            "migration_executed": False,
            "downgrade_executed": False,
        }

    latest_meta = index["snapshots"][0]
    latest_path = Path(str(latest_meta["path"]))
    latest = _evidence_item(latest_path, include_payload=True)
    return {
        "plan": "platform_product_journey_evidence_latest",
        "evidence_dir": index["evidence_dir"],
        "found": True,
        "snapshot": latest,
        "destructive_action_executed": False,
        "migration_executed": False,
        "downgrade_executed": False,
    }
